site_name: Reach RS docs
theme_dir: docstheme/material
site_favicon: favicon.ico
repo_url: https://github.com/emlid/reachrs-docs
extra:
  palette:
    primary: light blue
    accent: light blue
  logo: img/logo.png
  social:
    - type: github
      link: https://github.com/emlid
    - type: twitter
      link: https://twitter.com/emlidtech
    - type: facebook
      link: https://facebook.com/emlidtech
  google_analytics:
    - UA-49508097-6
    - auto
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)

pages:
- Introduction: index.md
- Power supply: power-supply.md
- Placement: placement.md
- ReachView app:
  - Introduction: common/reachview/index.md
  - Settings: common/reachview/settings.md
  - Status: common/reachview/status.md
  - RTK settings: common/reachview/rtk-settings.md
  - Correction input: common/reachview/correction-input.md
  - Position output: common/reachview/position-output.md
  - Base mode: common/reachview/base-mode.md
  - Logging: common/reachview/logging.md
  - Camera control: common/reachview/camera-control.md
  - Wi-Fi/Bluetooth: common/reachview/connectivity.md
  - Firmware reflashing: common/reachview/firmware-reflashing.md
  - Changelogs: common/reachview/changelogs.md
- LED status: led-status.md
- Specification: specs.md
- Quickstart: quickstart.md
- Tutorials:
  - How RTK works: common/tutorials/rtk-introduction.md
  - GPS post-processing: common/tutorials/gps-post-processing.md
  - Bluetooth output and Android mock location: common/tutorials/mock-location.md
