---
        model: M+
        power_port: JST-GH
        images:
          - '[![](img/reachm-plus/quickstart.png){: style="width: 200px;"}](quickstart.md)'
          - '[![](img/reachm-plus/tutorials.png){: style="width: 200px;"}](tutorials.md)'
          - '[![](img/reachm-plus/reachview.png){: style="width: 200px;"}](common/reachview)'
          - '[![](img/reachm-plus/antenna-placement.png){: style="width: 200px;"}](antenna-placement.md)'
          - '[![](img/reachm-plus/power-supply.png){: style="width: 200px;"}](power-supply.md)'
          - '[![](img/reachm-plus/specs.png){: style="width: 200px;"}](specs.md)'
        inthebox:
          - "* 1 x Reach M+ module"
          - "* 1 x USB cable" 
          - "* 1 x USB-OTG cable"
          - "* 1 x JST-GH 6-pin to jumper pin cable" 
          - "* 1 x JST-GH 5-pin to jumper pin cable"
          - "Optionally:" 
          - "* 1 x Tallysman multi-GNSS antenna" 
